### ISSUE TITLE
ChangeDraft 0.9.5のplugins/ChangeDraft/lib/MT/ChangeDraft/Util.pmについて

### ISSUE THREAD

**Issue by strktn** [ideamans/mt-plugin-change-draft#1]
ChangeDraft 0.9.0のファイルマップに存在していた以下のファイルが0.9.5に内包されていません。
extlib/MT/Ideamans/Store.pm

lib/MT/ChangeDraft/Util.pm L.8で以下の呼び出しをコメントアウトしない限り、MTの画面で
エラーとなります。
`#use MT::Ideamans::Store;`

コメントアウトしてエラーが表示されないようにした場合、他に影響があるのでしょうか。

**Comment by miyanaga** [comment]
ご指摘ありがとうございます。
削除忘れでして、先ほど変更をmasterにプッシュしました。
https://github.com/ideamans/mt-plugin-change-draft
